name: RasBeer ASCIIcat Mod
main: tk.rasmase.beer.Beer
version: 1.0.0
author: Rasmase & ASCIIcat
website: http://dev.bukkit.org/server-mods/rasbeer/
permissions:
    beer.beer.*:
        description: Gives access to all beer stuff
        children:
            beer.drink: true
            beer.brew: true
    beer.drink:
        description: Allows you to drink beer
        default: true
    beer.brew:
        description: Allows you to brew
        default: true
    beer.give:
        description: Allows you give away brews
        default: op
 
commands:
   beer:
      description: Basic beer command
